English vocabulary .
  * robust - 
  * broader - 
  * grasp - 
  * facilitate - 
  * hassle - 
  * obscured -
  * excess - 
  * constituents -
  * precise -
  * quirky -
  * conflated -
  * sophisticated -